apiVersion: apps/v1
kind: Deployment

metadata:
  name: qlik-challenge
  labels:
    app: qlik-challenge

spec:
  replicas: 2
  selector:
    matchLabels:
      app: qlik-challenge
  template:
    metadata:
      labels:
        app: qlik-challenge
    spec:
      containers:
        - name: qlikchallenge
          image: ghcr.io/benjaminhamon/qlikchallenge:develop
