apiVersion: v1
kind: Service

metadata:
  name: qlik-challenge
  labels:
    app: qlik-challenge

spec:
  selector:
    app: qlik-challenge
  ports:
    - protocol: TCP
      port: 9099
      targetPort: 9091
